import React, { Component } from 'react';
import '../App.css';
import AppNavbar from '../components/AppNavbar';
import Footer from '../components/Footer';
import { Container, Row, Col } from 'reactstrap';
// import ChroniclesHeader from '../components/ChroniclesHeader';
import mehdi from '../resources/images/chronicles/mehdiKargar.png';
import reflection from '../resources/images/chronicles/selfReflection.png';
import question from '../resources/images/chronicles/question.png';
import { Button } from 'react-bootstrap';

class BecomeStrongestPerson extends Component {
    render() {
        return (
            <div className="all-content">
                <div className="content-wrap">
                    <AppNavbar />
                    {/* <div className="blue-container">
                        <ChroniclesHeader />
                    </div> */}
                    <div className="main-page">
                        <Container className="text-center">
                            <h1>Become the Strongest Person</h1>
                            <h6 className="authors">BY YUCONG YANG &middot; RAY CHANG &middot; SELINA YANG &middot; SABRINA TENG &middot; NATHAN YANG &middot; HARRY SIO</h6>
                            <h6 className="date">November 19, 2021 &middot; 12 min read</h6>
                        </Container>
                        <a href="#" id="introduction"></a>
                        <Container className="text-center">
                            <img className="chronicle-pics" src={mehdi} alt="Mehdi's headshot" />
                        </Container>
                        <Container>
                            <Row>
                                <Col md="2"></Col>
                                <Col md="8">
                                    <br></br>
                                    <p>Dr. Mehdi Kargar is currently the CEO and co-founder of Maxterial, Inc, a material science startup company. Dr. Kargar has a Ph.D. in mechanical engineering at Virginia Tech, where he was working on bio-inspired nanotechnology-based boating and biomaterials. In his company, he is able to commercialize his expertise and provide affordable metallic coating to protect the surfaces while reducing the usage of environmentally toxic or carcinogenic coating material. He encourages young people to live a life where your life is alive and moving, rather than just following the track and trend that everybody else does.</p>
                                    <h1 className="text-center">&middot; &middot; &middot;</h1>
                                    <h2><strong>How would you describe what you're doing now professionally?</strong></h2>
                                    <p>My current job is the co-founder of a seven-year-old material science startup called Maxterial. The majority of my job is dealing with investors raising money, so we're dealing with customers. I also have to constantly find senior level people for my company, to try to bring them on board with the team and keep the company financially stable. Also, I have to put the vision for the company on where it's going to go, explain why those directions are the right directions, like how those directions are going to enable something good for humans, and also try to find the shareholders that care about good stuff. At the same time, I have to serve the benefit of shareholders – how can they get a very good return on their investment? So, these are the majority of the work I do as a professional.</p>
                                    <h2><strong>What is the driving force behind your work?</strong></h2>
                                    <p>I didn't intend to be a founder, but it just happened. Initially, I thought we were just publishing a paper, and somebody said we're going to become a company. At the beginning, I felt that there was no one who could be the CEO, and that's how I turned out to be the CEO. But regarding my driving force throughout these years, I had a couple of ambitious goals. On the environmental side, we're eliminating a very toxic chemical called hexavalent chromium or chromium 6, which was already used in the coating industry. Eventually they become part of your water system, and these chemicals cause cancer. So, we have been building the technology to fully eliminate them from our market. If that happens, it could be a good technology that helps to remove the bad chemicals from our water system, and we all get better water.</p>
                                    <p>Second, I’m concerned about the safety and life of the manufacturing laborers, as they are exposed to these chemicals every day. If they don’t have to be exposed to those chemicals, we can save their lives. At the same time, we also try to keep our manufacturing process simple so people can keep their job. If the manufacturing processes become too sophisticated, the majority of less educated people cannot keep their jobs. On the industrial side, major problems like corrosion occur. Many assets are corroded every year, and that is a trillion-dollar problem. [While trying to make the manufacturing process as environmentally friendly as possible], we also want to reduce the cost and reduce the carbon footprint of the manufacturing process.</p>
                                    <p>Also, we have an ambitious vision for the financial side. As I said, we always try to combine to do good and return good investment because I got people's money. The best thing I think we can be is the first possible unicorn in the chemical industry. If you look at the history, you see a lot of unicorns in pharmaceuticals and software, things like that, [but if you look at industrial chemical companies, there are not that many unicorns except for some big names like DuPont.] Our vision is to be something like that, and I think we are on our way to combine all these together.</p>
                                    <h2><strong>What is your background and how is it connected to your professional work?</strong></h2>
                                    <p>The title of my degree was always mechanical engineering. I had a bachelor, two masters and one PhD, all in mechanical engineering. But honestly, I don't think I've ever been a mechanical engineer. My first master’s degree was related to aerospace engineering and some chemistry, while my second master’s was mainly biomedical and chemical. I was making anti-bacterial and special coating. My PhD was mainly chemical – even my PhD advisor was not an engineer but a chemist. He was, I think, the Vice President of the American Chemical Society. My other advisor was a microbiologist and an environmental engineer. So, on the personal side, I think what changed my attitude toward business life and everything else was my working experience for a small company during my PhD. Actually, I met my wife there, and it was an entrepreneurial environment. We went to many companies, I think more than 10 or 11 companies, and we were exposed to all sorts of different industries – the edible oil industry, sugar industry, power industry, you name it. Because I was working on combustion equipment, which was everywhere, so I got to know a little bit of everything in the industry. Now when I start the company, I have to become a business to raise money, which are kind of like CFO type of things. So, that's a little bit of my life, and it is also my curiosity that always gave me value. I think you should live a life where your life is alive and moving, rather than just following the track and trend that everybody else does. That's my interpretation of living.</p>
                                    <h2><strong>In your eyes, what are the necessary qualities for someone to become a successful entrepreneur?</strong></h2>
                                    <p>To me it is just a matter of wanting to leave a good impact. If you just want to make a lot of money, or be the boss, these kinds of stuff are actually just illusions. When you go to real work, everybody is your boss, even your employees are your boss. Rather than having one boss, you have many of them! Regarding the point of making a lot of money, in the past 7 years I just paid myself the plain salary. If I were in Apple, I would be making at least one and a half million for the kind of job I do, maybe even more in seven years. The thing that matters is that you want to really leave a big impact. You have a vision that you really want to make a difference in the world. You must have that kind of vision, and that's the number one quality you need to have. When it goes into operation, you need to be able to build a team and raise money. If you are good with people, then you will know how to hire the right people who have the skills.</p>
                                    <h1 className="text-center">&middot; &middot; &middot;</h1>
                                    <h2><strong>What are the types of people that you recruit into your team?</strong></h2>
                                    <p>At the early stage of the company, I am mainly hiring senior people. The company has built this technology, and now I really need a senior person who has a lot of experience in my domain [to execute them]. This way, he knows the cost and he knows how to do it. Some analysts [in my team] have 34 years of experience. So, I try to recruit senior people and I let them hire the rest of the people.</p>
                                    <p>But there are many senior people just like other experienced people. Among all these senior people, there are some of them who have special drives. For example, if somebody is a good salesman and you really want him, but what is equally important is that he does not just care about making money. What is the thing that he's selling? What kind of qualities does he have? What kind of impact did he leave? [I am looking for all these] to find the more interesting person. Also, why do people want to come in [to our team]? If they only care about making some salary, they can go to Apple or Google, right? But some people really get to the point where they really want to do something big. Maybe they don't know how to start a company themselves. Maybe they don't want to take too much risk, but they still want to do something big. The first vice president we hired is about to retire, but when I met him, he said, “Look, I always wanted to start my own company. I never, I never could take a risk like that.” I said, “you know, you're a very capable person. Why don't you join us?” And he came in, and that person alone is doing the work that maybe even 10 people cannot do. Among your early employees, you really need to consider that. They shouldn't be driven by money or just jobs because they may leave you. Also they are not going to be helping you to change yourself and check your company.  Those types of people, even if their title is the co-founder, they don't really follow the rules and [will negatively impact] the culture of the company. [So, I think the key is to have people with] proper experience and having a good drive which comes out of their heart.</p>
                                    <h2><strong>What are your thoughts on being an effective leader and keeping the team motivated for the long run?</strong></h2>
                                    <p>That's actually one of the things I learned over the years. [At first, I thought I would just be a little boss], but then I hoped I could become a leader. A leader should be the example. If there is hard work that has to be done, he is the one who does it. If working over the weekend is sometimes needed, the leader is the one who does it first. He does not just order others to do that. </p>
                                    <p>Another thing, which is just my opinion and will depend on the size of the company, is that your employee shouldn't just be your employee. I think they should be your teammates. I don't call anyone an employee. I always call them teammates. I'm friends with everybody. They also see that I’m following the rules myself, and I'm not trying to ask people to follow a rule that I don't. In leadership I have to set rules and standards, which should be clear to everybody. Communication is also very important. People want to make sure they are heard, not just being ordered to do this and that. When you are listening to them it shows that they are important. And if they are important, they will be more willing to look up to your leadership. Another important thing I found is that the startup CEO should spread a vision that a teammate has to understand. Where is our goal? Why is this big? [The teammates] have to be updated on these on a regular basis, and I even report to them – we have done this. We have done that. Where are we right now and where is our goal? People will get excited!</p>
                                    <p>Empowering is also very important. Before empowering, you should make sure nobody ever puts anyone down. A lot of time in the business world they will put somebody down - you're only an engineer, or only a scientist. [That is a huge mistake.] They don't understand business language correctly because they have never been trained – they did not get those lectures and the business language is new to them. But they have been trained for something else, and everybody has something that they can be very good at. I think if people are getting paid less, but they feel motivated and empowered, they will still stay with the company. In fact, in the last one month, three employees of a well-established tech company came to me. They all want to quit their job and they want to learn how to start a company. I think empowering people is very important. Never let anyone put anyone down.</p>
                                    <p>And that ultimately goes to the leadership stuff. By the way, these are the things I hope I do, but I don't know if I can do them, even though I am doing my best. Years ago, I was not really good at it. I used to get frustrated when I was talking to one of my engineers, I asked him one question and he was talking about something else, so I would stop him. But now I stop them in a more respectful way and use the benefit of the doubt. Maybe I didn't ask the right question. Maybe I didn't make it clearer. So now I give them some credit for the idea they share, and I don’t stop others constantly [when they are speaking].</p>
                                    <p>[On a more fundamental level], I think if a leader is powerful inside, if a leader is not too insecure, that person naturally empowers other people. But if the person naturally is insecure, weak, then they put other people down. So, empowerment comes from people who are self-made, powerful, more experienced, more established, and more internally cohesive. Leaders also become more powerful when they empower other people. That's how I experienced it, because I made that mistake when I was younger and less experienced. Instead of empowering, I wanted to be powerful. And when I wanted to be powerful, I was actually the weakest. But when you empower other people and allow them to empower you, you become the strongest person. Recruiting also plays a role because if you recruit wrong people in the team, then all the things will go wrong. Even when you hire the wrong person, the way you deal with them is important. Within the benefit of doubt, try to see what's wrong [in the system that can be corrected, rather than assuming that person is just bad]. </p>
                                    <a href="#" id="hstips"></a>
                                    <h2><strong>Do you have any suggestions for addressing common roadblocks like lack of confidence and fear of failure?</strong></h2>
                                    <p>Well, one straightforward suggestion is to find a good mentor - somebody who can be honest with you, can tell you the truth, and has good knowledge. If no one tells you, you will never see it, right? There are the kinds of things that are very difficult to self-reflect and see, and somebody needs to show you that. For example, exposing the tough truth that you are not confident enough inside. That's the kind of things that I think is important. </p>
                                    <p>The second thing goes back again to the value system of people. If the value system is only driven by people saying good stuff about you, or you envision just to be a billionaire, to be famous and things like that… it will collapse. Something will go wrong someday, somewhere, and it will just collapse. But if your value systems go a little differently, in my opinion, you see things differently – I don't own these things. These are not owned by me. I'm responsible to take good care of them, and don't worry about payments and stuff like that. Sometimes I think, if you go and ask Elon Musk (I'm not giving him as an example. You may consider him good or bad, and I don't want to judge him at all), and say look, you're the richest person on planet Earth! Maybe he doesn't even know that. Maybe he doesn't even care about that. Maybe all he cares about is to own all the electric cars out there. He's not thinking of being famous or not famous. I want to be able to think like that, and really [focus on trying] to leave an impact. That's the part I was missing in my life. After I found it, that changed everything.</p>
                                    <div className="text-center">
                                        <img className="chronicle-pics" src={reflection} alt="self reflection" />
                                    </div>
                                    <br></br>
                                    <p>Another thing that I also want to tell you, is to have people around yourself that appreciate your growth. There are many things we don't know, so at each stage we may be less than someone in that specific approach and in that specific aspect. If you are dealing with people who constantly compare you with someone who is much better than you, a lot of time that [negatively] impacts your confidence and gets you into a different mode of operation. But if you also have people that appreciate your growth – for example, last year you had no idea how to raise money, but now you raised a million – that is another part that is very important. Be appreciative of our growth. I always tell people that in my opinion, happiness is not a matter of having. Happiness is a matter of gaining. If you get to the highest place, I don't know if you're going to feel any happiness. But when you're moving up, you feel happiness. I was at 900 feet yesterday but now I am at 1000 feet, and that's the kind of mindset that we have to build inside for our souls. At the beginning stage, a mentor, a friend or whoever can appreciate that, [is very important and can really help us]. That is my faith.</p>
                                    <p>You don’t want to become an egoistic person, but you also don’t want to become a weak person and never appreciate your own value. So [the key to] being at the balance point is always having self-reflections, having somebody who gives you feedback and somebody who believes in you. Also, remember to celebrate the small achievements. If you meet the milestone, even by a little bit, then go buy yourself a coffee or a gift or whatever. One thing that was missing in me is that I was constantly chasing the milestones. When I hit a milestone, I will immediately start looking at my next milestone. Don’t do this. Buy yourself an ice cream or buy for your teammates something appreciated. I think it's important to value our groups and be ambitious at the same time. Don't go for a small thing but take steps towards [your goal].</p>
                                    <h1 className="text-center">&middot; &middot; &middot;</h1>
                                    <h2 className="text-center"><strong>Tips for Finding a Mentor</strong></h2>
                                    <p>I think asking for help is the first step. When I talk to people that I may see they don't ask and I feel I can help them, I will try to probe them. You asked me this question, so do you know this? Do you know that? I will try to be a little bit outgoing because I know usually many people don't know but asking for help is the number one tool.</p>
                                    <p>Secondly, use your network very well. Somebody says network is net worth, so use your network to connect yourself to people. Maybe I need somebody who can speak Chinese really well, and people have different criteria the way they think of a mentor. Maybe I want an engineer who is also a woman. Sometimes people will just know a potential candidate, so I always try to use my network. </p>
                                    <p>My third point, again, goes to sincerity, honesty, and thinking of what you really want to do. A good mentor will always want to help somebody figure out things or go toward the goal. That's very important when you talk to some people. Actually, I have many good mentors, but I never thought about how I found them, even though I'm pretty good at finding them. For example, one of my mentors used to be Steve Jobs' lawyer. He taught me a lot about how he dealt with him, and I found him through my existing network. So, when I started my company, one of the alumni of my university became invested in my company and I told him that I need a good business mentor and asked if he knew anyone. Then he connected me to this person, made a good friend and that's how we found him. That's the number one person that I found. I can't remember how I found all my mentors, but I always ask for it. I don't just call some random person in the street. I think the first step is to look for it [, and know what you are looking for]. Also, when you become proactive, then when you let someone know that you are looking for a mentor, they can ask you relevant follow-up questions and the discussion can be continued. If somebody is admitting that I need help and I need to grow, people will try to clarify and help you – what do you mean by mentor? What do you need? That's the beginning of it. Even in that thought process, they will start wondering and asking themselves what they really need.</p>
                                    <p>But I want to say that I don't recall anybody calling me and saying, Look, Gavin can be a good mentor. It was always me asking for help first. And as soon as you see somebody that you think is a successful person, you can always ask. A mentor is not like a business partner; a mentor is there to help you. Maybe he knows what is good for you for one month, and then you find another one that is better [for that period]. I don't know if I'm giving you the right answer, but that's how I was doing my thing. When I was a student, I really needed somebody to teach me something about bacteria. I went to LinkedIn and started googling Virginia Tech, my school, and bacteria. When I found somebody in New York, I emailed him. I told him what I wanted to do and how I found him, and the guy answered my question! That's really making the most out of your network, and I am still constantly expanding mine.</p>
                                    <a href="#" id="collegetips"></a>
                                    <h1 className="text-center">&middot; &middot; &middot;</h1>
                                    <h2 className="text-center"><strong>Tips for College Students in Mechanical or Chemical Engineering</strong></h2>
                                    <p>Well, you know it depends on if they want to start a company and renovate. I think just try to be more than normal students in the college program. I suggest contributing to these extracurricular activities, like being a member of some student groups. Try to take some leadership position or make yourself have to deal with somebody. For example, in those student groups you might have to get some money from someone to buy pizza for the rest of the people, and these are the things that make you think of many aspects that you have never thought of. These are the things that require you to take a leadership position out of five other students, and you have to convince them so that they may follow you. Set yourself into a place that forces you to ask questions – can I do it? Why can’t I do it? Why do I fail? What can I do better? Ask other people for help. Don’t just try to google everything [by yourself].</p>
                                    <div className="text-center">
                                        <img className="chronicle-pics" src={question} alt="question" />
                                    </div>
                                    <br></br>
                                    <p>Number two, if they want to really be professional engineers, definitely go for an internship and don't stick to only school. When you go into an internship, the first thing you do is to sign an IP assignment. Now what is an IP assignment? I've never seen any document like that. [Just getting into that environment immediately will already make you learn so much.] [If you cannot find an internship,] at least if there are professional development courses in the school, take them. Even basic stuff, like how correct your lab notebook is, really impacts the person who wants to hire you. If you want to get into the starting company, how does entrepreneurship work? The majority of the schools nowadays have an entrepreneurship competition. At least go there, sit there, and see what these people are doing. Listen to their pitch, and that's going to really help you with a lot of these types of activities. I think these are the things people in school should do, and you should consider that as important, maybe even more important than whether they pass a course.</p>
                                    <p>Also, I think finding a mentor is the start of an exploration. If you are exploring then we will end up at the place where you will start to question yourselves and feel like you need a mentor, as you are just going through the typical terms of life. Sooner or later, you can understand that's not the way to live a life and you will start looking for somebody. But the fact that you are asking for mentors means that you are exploring, which is a very good sign. I think that's something we need. The fact that you are thinking means that you will ask questions, and you will try to find if anybody has ever done this because you don’t have to go through the same thing again and again. That's the whole point [of finding a mentor].</p>
                                </Col>
                                <Col md="2"></Col>
                            </Row>
                        </Container>
                        <Container className="main-page text-center">
                            <Button href="/chronicles" variant="info">All Chronicles</Button>
                        </Container>
                    </div>
                </div>
                <Footer />
            </div>
        );
    }
}

export default BecomeStrongestPerson;